NAME = 'ShareBot+'
TOKEN = ''
SUPPORT_SERVER = ''
BUMP_RATE_LIMIT = 3600
USE_BUTTONS = True
STATUS_MESSAGES = ['waiting for servers', 'sharing your discord', 'free advertisement']
STATUS_CHANGE_DELAY = 3 # minimum: 3 (seconds)
DATABASE = 'db.sqlite3'
ENABLE_PREMIUM = True
EMBED_COLOR = "none" # teal, purple, yellow, blue, green, pink, black, lavender, crimson, none
EPHEMERAL_MESSAGES = True
ADMINS = [1024738028301865031, 1145676460225478686] # List of bot administrators (USER IDS)
